#pragma once

#include "sprite.h"
#include <vector>


class Map
{
	public:
		Map();
		void print_map();

	private:
		const char wall_ = Sprite::walls;
		const char rocks_ = Sprite::rocks;
		const char ground_ = Sprite::ground;
		std::vector<std::vector<char> > map
		{{wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, Sprite::trap, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, rocks_, rocks_, rocks_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, rocks_, rocks_, rocks_, rocks_, rocks_, ground_, ground_, ground_, ground_, Sprite::trap, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, Sprite::potion, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, Sprite::potion, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, Sprite::trap, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, Sprite::trap, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, rocks_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, rocks_, rocks_, rocks_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, rocks_, rocks_, rocks_, rocks_, rocks_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, Sprite::potion, ground_, ground_, Sprite::trap, ground_, ground_, Sprite::potion, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, ground_, wall_},
		{wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_, wall_}};
};